/**
 * Common actions For the app
 */

module.exports = {
  SNACKBAR_FAIL: 'SNACKBAR_FAIL',
  SNACKBAR_SUCCESS: 'SNACKBAR_SUCCESS',
  SNACKBAR_CLOSE: 'SNACKBAR_CLOSE',
  UPDATE_STAYOVERS: 'UPDATE_STAYOVERS',
  UPDATE_AVAILABLE: 'UPDATE_AVAILABLE',
  UPDATE_CHECKIN: 'UPDATE_CHECKIN',
};
