/**
 * Actions for Loading DailyReport
 */

module.exports = {
  UPDATE_REPORT: 'UPDATE_REPORT',
  UPDATE_HOUSEKEEPING_REPORT: 'UPDATE_HOUSEKEEPING_REPORT',
  LOAD_MAINTENANCE_LOG: 'LOAD_MAINTENANCE_LOG',
  UPDATE_REPORT_REFUND: 'UPDATE_REPORT_REFUND',
};
