/**
 * Actions for Report State
 */
module.exports = {
  LOAD_PEND_RESERVATION_SUCCESS: 'LOAD_PEND_RESERVATION_SUCCESS',
  LOAD_CURR_RESERVATION_SUCCESS: 'LOAD_CURR_RESERVATION_SUCCESS',
  LOAD_OVER_RESERVATION_SUCCESS: 'LOAD_RESERVATION_SUCCESS',
};
